### ISSUE TITLE
Missing library libreadline, any hints?

### ISSUE THREAD

**Issue by mslatour** [thetrime/heroku-prolog-buildpack#1]
I understand this buildpack is a very rough skeleton. It however seems you've gotten farther than I've got, so perhaps you could give me a hint.

I've created a fresh heroku app with your buildpack, using
`heroku create <name> --buildpack https://github.com/thetrime/heroku-prolog-buildpack`

And I've cloned https://github.com/thetrime/prolog-getting-started and pushed the files to the new heroku app. However it failed while compiling Prolog on a missing library.

```
Initializing repository, done.
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (9/9), 2.08 KiB | 0 bytes/s, done.
Total 9 (delta 0), reused 0 (delta 0)

-----> Fetching custom git buildpack... done
-----> Prolog app detected
------> Checking for precompiled Prolog build
------> Found precompiled Prolog build!
-----> Compiling slug
/app/.local/bin/swipl: error while loading shared libraries: libreadline.so.5: cannot open shared object file: No such file or directory

 !     Push rejected, failed to compile Prolog app
```

Is there something I forgot to do? Or did the heroku environment just change?

**Comment by yansh** [comment]
@mslatour did you get it working?

**Comment by thetrime** [comment]
Hmm. If libreadline isn't available this should be pretty easy to fix by just passing --without-readline to configure. I'll hopefully get some time to have a look in the near future. Somehow I missed mslatour's original opening of the issue 2 months ago!

**Comment by yansh** [comment]
@thetrime Thank you. Do you mean to recompile the prolog environment?

**Comment by thetrime** [comment]
Yes, exactly. After a little more digging I realise the problem is probably that this buildpack is 2 /years/ old now and heroku has moved on from libreadline5 to libreadline6. I've recompiled Prolog and it works fine, but I haven't quite had time to update the package. Should be done by tomorrow though, and as a bonus the version of swipl will be bumped to 7.3.20

I've also created a repo specifically for compiling other versions too. If you can't wait 24 hours then have a look at https://github.com/thetrime/swipl-heroku - it's its own buildpack (how meta is that?) but all you need to do once you've deployed it is to connect to a bash instance in your app and run ./compile.sh 7.3.20 (or any other version) and then somehow get the env-7.3.20.tar.bz2 out of the app and into a buildpack forked from this one. If that sounds too hard, simply wait :)

**Comment by yansh** [comment]
@thetrime thank you. I can wait :)

**Comment by thetrime** [comment]
That seems to do the trick. So long as you don't specify that you want 7.1.23 in your manifest, you'll now get 7.3.20, which seems to work fine.

**Comment by yansh** [comment]
Thanks Matt! Much appreciated. Seems to work! 👍
